import type { Metadata } from "next";
import "./globals.css";


import Providers from "@/components/Providers";

import { ThemeProvider } from "@/components/theme-provider"
import {NextIntlClientProvider} from 'next-intl';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  
}



export default async function RootLayout({
  children,
}: Props) {

  


  return (
    <html suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <Providers>
          
        
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider>
        {children}
        </NextIntlClientProvider>
        </ThemeProvider>
        
        </Providers>
      </body>
    </html>
  );
}
